---
title: "Mini Project 2"
author: "Vatsala, Emma, Margaret"
date: "3/8/2019"
output: html_document
code_folding: hide
---

```{r message = FALSE, echo = FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r message = FALSE, echo = FALSE, warning = FALSE, results='hide'}
join_df <- house_elections %>%
              left_join(committees, by=c("state"= "cmte_state"))
join_df
# joining the house elections and committees dataframes to have candidates and the comittees who gave them money. We are joining by their common variable, state.
```


```{r message = FALSE, echo = FALSE, warning = FALSE,results='hide'}
fec_df<- join_df %>%
      select(state, candidate_name, party, general_votes, incumbent, cmte_name)

fec_df
#selecting only the variables that we need from the previous data frame
```


```{r message = FALSE, echo = FALSE, warning = FALSE, results='hide'}
contributions_df <- contributions %>%
  select(name,transaction_amt,transaction_type, state)%>%
  filter(transaction_amt >0)

contributions_df
# Selecting the useful variables from the contributions data frame and then filtering to only get contributions that werent returned. 
```


```{r message = FALSE, echo = FALSE, warning = FALSE, results='hide'}
contributions_fec <- fec_df %>%
    left_join(contributions_df, by = c("cmte_name" = "name"))%>%
    filter(!is.na(transaction_amt)) %>%
  group_by(state.x) %>%
  arrange(state.x)

contributions_fec
# joining the contributions data frame and the fec data frame by name. We are filtering to remove the NA values and grouping by and arranging by state
```



```{r message = FALSE, echo = FALSE, warning = FALSE, results='hide'}
sum_money<- contributions_fec %>%
  group_by(cmte_name) %>%
  summarize( sum_money = sum(transaction_amt))

sum_money
# finding the sum of each committees donations
```



```{r message = FALSE, echo = FALSE, warning = FALSE}
general_votes_df <- contributions_fec %>%
  left_join(sum_money, by = "cmte_name") %>%
  filter(transaction_type== c("24A", "24E"), state.x == "NY") %>%
  select(state.x, party, general_votes, incumbent, candidate_name, cmte_name, transaction_amt, transaction_type, sum_money)

general_votes_df
#Joining the data sets so we can have each candidate, their status of imcumbancy, the total amount of money they received from each committee, and the total amount of general votes they received. We are filtering so we have both how much money was used against the candidate and how much mone was used in their favor. We can use this to see each party and how many votes they received. 
```


```{r message = FALSE, echo = FALSE, warning = FALSE} 
donations_df <- contributions_fec %>%
  left_join(sum_money, by = "cmte_name")%>%
  filter(transaction_type==c("24E", "24A"), state.x == "NY")%>%
  select(state.x, candidate_name, party, general_votes, incumbent, transaction_type, sum_money)%>%
  group_by(transaction_type, party)%>%
  summarise(new_sum=sum(sum_money))

donations_df
# Doing the same thing as the data frame above but now groupnig by the transaction type. We want to see how much money was used both in favor of a party and against a party. 
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
general_votes_plot <- ggplot(general_votes_df, aes(x = party, y = general_votes)) + 
  geom_col(position = position_dodge(), width=0.5,fill="#A4A4A4")+
   scale_x_discrete(label = c("Conservative","Democrat","Green", "Libertarian","Republican","Socialist", "Write In"))+
  labs(title = "Total General Votes Each Party Received", x = "Party", y = "General Votes")+
  theme_minimal()
  

general_votes_plot
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
donations_plot <- ggplot(donations_df, aes(x = party, y = new_sum, fill = transaction_type))+
  geom_col(position = position_dodge())+
     scale_x_discrete(label = c("Conservative","Democrat","Green", "Libertarian","Republican","Socialist", "Write In"))+
   scale_fill_manual(name="Transaction Type",values = c("#CC6666", "#9999CC"),labels=c("Money Used Against a Party", "Money Used For a Party"))+
  theme_minimal()+
  theme(legend.position = "top")+
  labs(title = "Amount of Money used for and Against each Party", y = "Amount of Money", x = "Party")

donations_plot
```

